### PR TITLE
confused

### PR DESCRIPTION
**Pull request by lemonorangelime**
`makeActualVisit` isnt defined, so this seems to have no use?

### CODE REVIEW

**Comment by lemonorangelime** [comment]
image

**Comment by sys-256** [comment]
It was for a backend I made, to test. But i have some major bugs which crash the whole application and i'm too lazy to fix them

**Comment by sys-256** [comment]
also, makeActualVisit is defined in the file which is hosted on the backend

**Comment by lemonorangelime** [comment]
dead

**Pull request closed without merging**
